/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btc6_bt2;

/**
 *
 * @author Windows 10 Pro
 */
public class Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form BT2_BTC6
     */
    public Main_Form() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jProgressBar1 = new javax.swing.JProgressBar();
        Panelball = new javax.swing.JPanel();
        btnAddBall = new javax.swing.JButton();
        btnSpeedDown = new javax.swing.JButton();
        btnSpeedUp = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        lblNumberBall1 = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        lblNumberBall3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bóng chạy");

        Panelball.setBackground(new java.awt.Color(255, 255, 255));
        Panelball.setPreferredSize(new java.awt.Dimension(600, 330));

        javax.swing.GroupLayout PanelballLayout = new javax.swing.GroupLayout(Panelball);
        Panelball.setLayout(PanelballLayout);
        PanelballLayout.setHorizontalGroup(
            PanelballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        PanelballLayout.setVerticalGroup(
            PanelballLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        btnAddBall.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddBall.setText("Thêm bóng");
        btnAddBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBallActionPerformed(evt);
            }
        });

        btnSpeedDown.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSpeedDown.setText("Giảm tốc");
        btnSpeedDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeedDownActionPerformed(evt);
            }
        });

        btnSpeedUp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSpeedUp.setText("Tăng tốc");
        btnSpeedUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeedUpActionPerformed(evt);
            }
        });

        lblNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNumber.setText("0");

        lblNumberBall1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNumberBall1.setText("Số lượng:");

        lblSpeed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSpeed.setText("50");

        lblNumberBall3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNumberBall3.setText("Tốc độ:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panelball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddBall, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpeedUp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSpeedDown, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumberBall1)
                            .addComponent(lblNumberBall3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpeed)
                            .addComponent(lblNumber))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panelball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSpeedDown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSpeedUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumberBall1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumberBall3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6))))
                    .addComponent(btnAddBall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    MoveBall[] ball=new MoveBall[100];
    int n = 0;
    int speed = 50;
    int RealSpeed=10;
    boolean flagUp = true;
    boolean flagDown = true;
    
    private void btnAddBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBallActionPerformed

        ball[n]=new MoveBall(Panelball.getGraphics(),speed);
        Thread t=new Thread(ball[n]);
        n++;
        lblNumber.setText(n + "");
        
        t.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddBallActionPerformed

    private void btnSpeedUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeedUpActionPerformed

        speed = speed - 5;
        if(speed <=0)
            speed = 1;
        for (int i = 0; i < n; i++) {
            ball[i].setSpeed(speed);
        }
        if (flagUp == true) {
            RealSpeed = RealSpeed + speed;
            flagUp = false;
        }
        else
        {
            lblSpeed.setText(RealSpeed+"");
            RealSpeed = RealSpeed + 5;
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpeedUpActionPerformed

    private void btnSpeedDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeedDownActionPerformed

        speed = speed + 5;
        for (int i = 0; i < n; i++) {
            ball[i].setSpeed(speed);
        }
        if (RealSpeed <= 0) {
            speed = 100;
            RealSpeed = 0;
            lblSpeed.setText(RealSpeed+"");
        }
        else
        {
            lblSpeed.setText(RealSpeed+"");
            RealSpeed = RealSpeed - 5;
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpeedDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelball;
    private javax.swing.JButton btnAddBall;
    private javax.swing.JButton btnSpeedDown;
    private javax.swing.JButton btnSpeedUp;
    private java.awt.Canvas canvas1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblNumberBall1;
    private javax.swing.JLabel lblNumberBall3;
    private javax.swing.JLabel lblSpeed;
    // End of variables declaration//GEN-END:variables
}
