/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BTVN4_BT2;

import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10 Pro
 */
public class PhuongTrinhBac2 extends javax.swing.JFrame {

    /**
     * Creates new form GiaiPTB2JFrame
     */
    public PhuongTrinhBac2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        soA = new javax.swing.JTextField();
        soB = new javax.swing.JTextField();
        soC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nghiemx1 = new javax.swing.JTextField();
        GPTB2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        nghiemx2 = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình giải phương trình bậc 2");

        jLabel1.setText("NHẬP A");

        jLabel2.setText("NHẬP B");

        jLabel4.setText("NHẬP C");

        soA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soAActionPerformed(evt);
            }
        });

        soB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soBActionPerformed(evt);
            }
        });

        soC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soCActionPerformed(evt);
            }
        });

        jLabel5.setText("NGHIỆM");

        GPTB2.setText("GIẢI PHƯƠNG TRÌNH");
        GPTB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPTB2ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PHƯƠNG TRÌNH CÓ DẠNG ax² + bx + c = 0");

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soA, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soB, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nghiemx1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nghiemx2))
                        .addComponent(soC, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GPTB2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nghiemx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(nghiemx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GPTB2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soAActionPerformed
        String numberA = soA.getText();
        soA.setText(numberA);

// TODO add your handling code here:
    }//GEN-LAST:event_soAActionPerformed

    private void soBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soBActionPerformed
        String numberB = soB.getText();
        soB.setText(numberB);
        // TODO add your handling code here:
    }//GEN-LAST:event_soBActionPerformed

    private void soCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soCActionPerformed
        String numberC = soC.getText();
        soC.setText(numberC);
        // TODO add your handling code here:
    }//GEN-LAST:event_soCActionPerformed

    private void GPTB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPTB2ActionPerformed
        if (!soA.getText().equals("")) {
            if (!soB.getText().equals("")) {
                if (!soC.getText().equals("")) {
                    float delta = (Integer.parseInt(soB.getText()) * Integer.parseInt(soB.getText()))-(4 * Integer.parseInt(soA.getText()) * Integer.parseInt(soC.getText()));
                    if (delta < 0) {
                        JOptionPane.showMessageDialog(rootPane, "Phương trình vô nghiệm");
                    }
                    if (delta == 0) {
                        float nghiemKep = -1 * Integer.parseInt(soB.getText()) / 2 *Integer.parseInt(soA.getText());
                        nghiemx1.setText("x1 = "+nghiemKep);
                        nghiemx2.setText("x2 = "+nghiemKep);
                        JOptionPane.showMessageDialog(rootPane, "Phương trình có nghiệm kép");
                    }
                    if (delta > 0) {
                        float x1 = (float) ((-1 * Integer.parseInt(soB.getText()) + Math.sqrt(delta)) / (2 * Integer.parseInt(soA.getText())));
                        float x2 = (float) ((-1 * Integer.parseInt(soB.getText()) + -1 * Math.sqrt(delta)) / (2 * Integer.parseInt(soA.getText())));
                        nghiemx1.setText("x1 = "+x1);
                        nghiemx2.setText("x2 = "+x2);
                        JOptionPane.showMessageDialog(rootPane, "Phương trình có 2 nghiệm phân biệt");
                    }
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu C !!!");
                }
            }
            else    {
                    if (!soC.getText().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu B !!!");
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu B và C !!!");
                    }
                }
        }
        else {
            if (soB.getText().equals("")){
                if (soC.getText().equals("")){
                    JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu A, B và C !!!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu A và B!!!");
                }
            }
            else{
                if (!soB.getText().equals("")){
                    if (!soC.getText().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu A!!!");
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Bạn nhập thiếu A và C!!!");
                    }
                }  
            }
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_GPTB2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhuongTrinhBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhuongTrinhBac2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GPTB2;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nghiemx1;
    private javax.swing.JTextField nghiemx2;
    private javax.swing.JTextField soA;
    private javax.swing.JTextField soB;
    private javax.swing.JTextField soC;
    // End of variables declaration//GEN-END:variables
}
