
import Function.AutoID;
import Function.DonHang;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import Function.KhachHang;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.TableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author infov
 */
public class fKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form fKhachHang
     */
    String tenMenu, username;

    public fKhachHang(String tenMenu, String usernameString) {
        initComponents();
        this.tenMenu = tenMenu;
        this.username = usernameString;
        
        if(tenMenu.equals("NhanVien"))
            btnDeteleStaff.setEnabled(false);
        
        this.setLocationRelativeTo(null);

        Border panBorder = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        panelMain.setBorder(panBorder);

        LoadKhachHang();
    }

    private fKhachHang() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlTT = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdStaff = new javax.swing.JTextField();
        txtNameStaff = new javax.swing.JTextField();
        txtAddressStaff = new javax.swing.JTextField();
        txtNumberStaff = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFamale = new javax.swing.JRadioButton();
        dpNgaySinh = new org.jdesktop.swingx.JXDatePicker();
        iconAuto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnInsertStaff = new javax.swing.JButton();
        btnDeteleStaff = new javax.swing.JButton();
        btnExitStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rdbMa = new javax.swing.JRadioButton();
        rdbTen = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStaff = new javax.swing.JTable();
        lblMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelMain.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");

        pnlTT.setBackground(new java.awt.Color(204, 204, 255));
        pnlTT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "THÔNG TIN CHI TIẾT KHÁCH HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 10))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("MÃ SỐ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("TÊN");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("ĐỊA CHỈ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("GIỚI TÍNH");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("SỐ DT");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("NGÀY SINH");

        txtIdStaff.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtNameStaff.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtAddressStaff.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtNumberStaff.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtNumberStaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumberStaffKeyPressed(evt);
            }
        });

        rdbMale.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rdbMale.setSelected(true);
        rdbMale.setText("Nam");

        rdbFamale.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup2.add(rdbFamale);
        rdbFamale.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rdbFamale.setText("Nữ");

        dpNgaySinh.setToolTipText("");
        dpNgaySinh.setDate(new Date());

        iconAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/auto.png"))); // NOI18N
        iconAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAutoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTTLayout = new javax.swing.GroupLayout(pnlTT);
        pnlTT.setLayout(pnlTTLayout);
        pnlTTLayout.setHorizontalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(txtNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconAuto)))
                .addGap(80, 80, 80)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(rdbMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbFamale)))
                .addGap(59, 59, 59)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumberStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(dpNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        pnlTTLayout.setVerticalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTTLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(dpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumberStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTTLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtIdStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iconAuto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTLayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtAddressStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)))
                                .addGroup(pnlTTLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(rdbMale)
                                        .addComponent(rdbFamale))
                                    .addGap(27, 27, 27))))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 10))); // NOI18N

        btnInsertStaff.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btnInsertStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/insertClient.png"))); // NOI18N
        btnInsertStaff.setText("THÊM");
        btnInsertStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertStaffActionPerformed(evt);
            }
        });

        btnDeteleStaff.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btnDeteleStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/deteleClient.png"))); // NOI18N
        btnDeteleStaff.setText("XÓA");
        btnDeteleStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeteleStaffActionPerformed(evt);
            }
        });

        btnExitStaff.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExitStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/exitClient.png"))); // NOI18N
        btnExitStaff.setText("THOÁT");

        btnUpdateStaff.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btnUpdateStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/updateClient.png"))); // NOI18N
        btnUpdateStaff.setText("SỬA");
        btnUpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStaffActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("TÌM KIẾM: ");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rdbMa.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdbMa);
        rdbMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMa.setText("Mã");

        rdbTen.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdbTen);
        rdbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbTen.setText("Tên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnInsertStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeteleStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExitStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbMa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(rdbTen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(rdbMa)
                                .addComponent(rdbTen))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnExitStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnUpdateStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeteleStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        TableStaff.setBackground(new java.awt.Color(204, 204, 255));
        TableStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SỐ", "TÊN", "GIỚI TÍNH", "ĐỊA CHỈ", "NGÀY SINH", "SỐ DT"
            }
        ));
        TableStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableStaff);

        lblMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMenu.setText("MENU");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblMenu)
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(pnlTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertStaffActionPerformed

        // TODO add your handling code here:
        ThemKhachHang();
        LoadKhachHang();
    }//GEN-LAST:event_btnInsertStaffActionPerformed

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked

        if (tenMenu.equalsIgnoreCase("admin")) {
            fMenuAdmin admin = new fMenuAdmin(username);
            this.dispose();
            admin.setVisible(true);
        } else {
            fMenuNhanVien nhanVien = new fMenuNhanVien(username);
            this.dispose();
            nhanVien.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuMouseClicked

    private void txtNumberStaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumberStaffKeyPressed
        // TODO add your handling code here:
        String value = txtNumberStaff.getText();
        int l = value.length();
        if (evt.getKeyChar() == '\b' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && l < 10)) {
            txtNumberStaff.setEditable(true);
        } else {
            txtNumberStaff.setEditable(false);
        }
    }//GEN-LAST:event_txtNumberStaffKeyPressed

    private void btnDeteleStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeteleStaffActionPerformed
        // TODO add your handling code here:
        XoaKhachHang();
        LoadKhachHang();
    }//GEN-LAST:event_btnDeteleStaffActionPerformed

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed
        // TODO add your handling code here:
        SuaKhachHang();
        LoadKhachHang();
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void iconAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAutoMouseClicked
        // TODO add your handling code here:
        txtIdStaff.setText(AutoID.Instance().phatSinhIDKhachHang());
    }//GEN-LAST:event_iconAutoMouseClicked

    private void TableStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStaffMouseClicked
        // TODO add your handling code here:

        //lấy giá trị
        int dong = TableStaff.getSelectedRow();
        TableModel model = TableStaff.getModel();

        txtIdStaff.setText(model.getValueAt(dong, 0).toString());
        txtNameStaff.setText(model.getValueAt(dong, 1).toString());
        txtAddressStaff.setText(model.getValueAt(dong, 4).toString());
        txtNumberStaff.setText(model.getValueAt(dong, 5).toString());

        if (model.getValueAt(dong, 2).equals("Nam")) {
            rdbMale.setSelected(true);
        } else {
            rdbFamale.setSelected(true);
        }

        String dateString = model.getValueAt(dong, 3).toString();

        Date date = null;
        try {
            date = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(dateString);
        } catch (ParseException ex) {
            Logger.getLogger(fNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        dpNgaySinh.setDate(date);
    }//GEN-LAST:event_TableStaffMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TimKiem();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fKhachHang().setVisible(true);
            }
        });
    }
    
    //load header
    void LoadHeader(){
        TableStaff.getColumnModel().getColumn(0).setHeaderValue("Mã khách hàng");
        TableStaff.getColumnModel().getColumn(1).setHeaderValue("Tên khách hàng");
        TableStaff.getColumnModel().getColumn(2).setHeaderValue("Giới tính");
        TableStaff.getColumnModel().getColumn(3).setHeaderValue("Năm sinh");
        TableStaff.getColumnModel().getColumn(4).setHeaderValue("Địa chỉ");
        TableStaff.getColumnModel().getColumn(5).setHeaderValue("Số điện thoại");
    }

    //check null
    boolean kiemTraRong(JPanel panel) {
        for (Component c : panel.getComponents()) {
            if (c instanceof JTextField) {
                if (((JTextField) c).getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng không để trống!");
                    return false;
                }
            }

        }
        return true;
    }

    //tim kiem
    void TimKiem() {
        if (rdbMa.isSelected()) {
            TableStaff.setModel(KhachHang.Instance().TimKiemKH("mskh", txtTimKiem.getText()));
        } else {
            TableStaff.setModel(KhachHang.Instance().TimKiemKH("tenkh", txtTimKiem.getText()));
        }
    }

    //load Khach hang
    void LoadKhachHang() {
        TableStaff.setModel(KhachHang.Instance().LoadKhachHang());
        LoadHeader();
    }

    //Them khach hang
    void ThemKhachHang() {
        if(!kiemTraRong(pnlTT))
            return;
        
        String maso, ten, gioitinh, diachi, sdt, ngaysinh;

        maso = txtIdStaff.getText();
        ten = txtNameStaff.getText();

        if (rdbMale.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "Nữ";
        }
        diachi = txtAddressStaff.getText();
        sdt = txtNumberStaff.getText();

        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");

        ngaysinh = formater.format(dpNgaySinh.getDate());

        if (KhachHang.Instance().ThemKhachHang(maso, ten, gioitinh, ngaysinh, diachi, sdt)) {
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }

    }

    //xoa khach hang
    void XoaKhachHang() {
        //lay ma khach hang
        int dong = TableStaff.getSelectedRow();
        if (dong == -1) {
            JOptionPane.showMessageDialog(this, "Bạn có chọn dòng nào đâuuuuuuuu !");
            return;
        }
        int n = JOptionPane.showConfirmDialog(
                this,
                "Việc xóa thông tin khách hàng sẽ xóa cả thông tin hóa đơn của khách hàng. Bạn có chắc muốn xóa?",
                "Thông báo",
                JOptionPane.OK_CANCEL_OPTION);

        TableModel model = TableStaff.getModel();

        String maso = model.getValueAt(dong, 0).toString();

        //xóa luôn hóa đơn
        if (n == JOptionPane.OK_OPTION) {
            if (KhachHang.Instance().XoaKHVaHD(maso)) {
                JOptionPane.showMessageDialog(this, "Xóa khách hàng thành công!");
            }
        }

    }

    //sua khach hang
    void SuaKhachHang() {
        //lay ma khach hang
        int dong = TableStaff.getSelectedRow();
        if (dong == -1) {
            JOptionPane.showMessageDialog(this, "Bạn có chọn dòng nào đâuuuuuuuu !");
            return;
        }
        TableModel model = TableStaff.getModel();

        String maso = model.getValueAt(dong, 0).toString();

        String masomoi, ten, gioitinh, diachi, sdt, ngaysinh;

        masomoi = txtIdStaff.getText();
        ten = txtNameStaff.getText();

        if (rdbMale.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "Nữ";
        }
        diachi = txtAddressStaff.getText();
        sdt = txtNumberStaff.getText();

        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");

        ngaysinh = formater.format(dpNgaySinh.getDate());

        //
        if (KhachHang.Instance().SuaKH(maso, masomoi, ten, gioitinh, ngaysinh, diachi, sdt)) {
            JOptionPane.showMessageDialog(this, "Đã sửa khách hàng!");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableStaff;
    private javax.swing.JButton btnDeteleStaff;
    private javax.swing.JButton btnExitStaff;
    private javax.swing.JButton btnInsertStaff;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private org.jdesktop.swingx.JXDatePicker dpNgaySinh;
    private javax.swing.JLabel iconAuto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel pnlTT;
    private javax.swing.JRadioButton rdbFamale;
    private javax.swing.JRadioButton rdbMa;
    private javax.swing.JRadioButton rdbMale;
    private javax.swing.JRadioButton rdbTen;
    private javax.swing.JTextField txtAddressStaff;
    private javax.swing.JTextField txtIdStaff;
    private javax.swing.JTextField txtNameStaff;
    private javax.swing.JTextField txtNumberStaff;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
