
import DoiTuong.*;
import Function.AutoID;
import Function.DataProvider;
import Function.DonHang;
import Function.KhachHang;
import Function.NhanVien;
import Function.TTDonHang;
import Function.Tivi;
import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author infov
 */
public class fLapHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form fLapHoaDon
     */
    String tenMenu, username;
    long thanhtien = 0;
    int typeCheck = 0; //1 la check mahang, 2 la check tenhang, 3 la check gia

    String mahd_temp;

    public fLapHoaDon(String tenMenu, String usernameString) {
        initComponents();
        this.tenMenu = tenMenu;
        this.username = usernameString;
        this.setLocationRelativeTo(null);

        //Đường viền panelMain
        Border panBorder = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        panelMain.setBorder(panBorder);

        LoadAllCbb();
    }

    private fLapHoaDon() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSanPham = new javax.swing.JTable();
        lblMenu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbMaNV = new javax.swing.JComboBox<>();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayBan = new javax.swing.JTextField();
        cbbmakh = new javax.swing.JComboBox<>();
        txtTenKH = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        pnlTT = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lbCore = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtKhuyenMai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        txtSLKho = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbbmatv = new javax.swing.JComboBox<>();
        txtGia = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btnTaoHD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelMain.setBackground(new java.awt.Color(0, 255, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LẬP HÓA ĐƠN");

        jPanel3.setBackground(new java.awt.Color(0, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MỤC SẢN PHẨM CẦN THANH TOÁN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        TableSanPham.setBackground(new java.awt.Color(0, 255, 153));
        TableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSanPham);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        lblMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMenu.setText("MENU");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa đơn"));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel2.setText("MÃ HÓA ĐƠN");

        txtMaHD.setEditable(false);

        jLabel3.setText("NGÀY BÁN");

        jLabel4.setText("MÃ NHÂN VIÊN");

        cbbMaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbMaNVItemStateChanged(evt);
            }
        });

        txtDiaChi.setEditable(false);

        jLabel6.setText("TÊN KHÁCH HÀNG");

        jLabel5.setText("MÃ KHÁCH HÀNG");

        jLabel7.setText("ĐỊA CHỈ");

        txtNgayBan.setEditable(false);

        cbbmakh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbmakhItemStateChanged(evt);
            }
        });

        txtTenKH.setEditable(false);

        jLabel15.setText("TÊN NHÂN VIÊN");

        txtTenNV.setEditable(false);

        jLabel16.setText("SỐ ĐIỆN THOẠI");

        txtSdt.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(16, 16, 16)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChi)
                            .addComponent(cbbmakh, 0, 205, Short.MAX_VALUE)
                            .addComponent(txtTenKH)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)
                        .addGap(16, 16, 16)
                        .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlTT.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản phẩm"));

        lb1.setText("TÊN HÀNG");

        lbCore.setText("MÃ HÀNG");

        lb2.setText("ĐƠN GIÁ");

        jLabel11.setText("SỐ LƯỢNG");

        txtSL.setText("1");
        txtSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSLKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSLKeyTyped(evt);
            }
        });

        jLabel12.setText("KHUYẾN MÃI");

        txtKhuyenMai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKhuyenMaiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKhuyenMaiKeyTyped(evt);
            }
        });

        jLabel13.setText("THÀNH TIỀN");

        txtThanhTien.setEditable(false);

        txtSLKho.setEditable(false);

        jLabel14.setText("/");

        cbbmatv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbmatvItemStateChanged(evt);
            }
        });

        txtGia.setEditable(false);
        txtGia.setToolTipText("");

        txtTen.setEditable(false);

        javax.swing.GroupLayout pnlTTLayout = new javax.swing.GroupLayout(pnlTT);
        pnlTT.setLayout(pnlTTLayout);
        pnlTTLayout.setHorizontalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSLKho, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(lbCore)
                        .addGap(18, 18, 18)
                        .addComponent(cbbmatv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(lb1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lb2))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThanhTien)
                    .addComponent(txtGia))
                .addGap(44, 44, 44))
        );
        pnlTTLayout.setVerticalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(lb2)
                    .addComponent(lbCore)
                    .addComponent(cbbmatv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSLKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnthem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnthem.setText("THÊM / XÓA");
        btnthem.setEnabled(false);
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnluu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnluu.setText("LƯU / IN HD");
        btnluu.setEnabled(false);
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnTaoHD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTaoHD.setText("TẠO HD");
        btnTaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblMenu)
                        .addGap(263, 263, 263)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(127, 127, 127))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMainLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTaoHD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked

        if (tenMenu.equalsIgnoreCase("admin")) {
            fMenuAdmin admin = new fMenuAdmin(tenMenu);
            this.dispose();
            admin.setVisible(true);
        } else {
            fMenuNhanVien nhanVien = new fMenuNhanVien(tenMenu);
            this.dispose();
            nhanVien.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed

        // TODO add your handling code here:
        ThemHD();

    }//GEN-LAST:event_btnthemActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        btnTaoHD.setEnabled(true);
        btnthem.setEnabled(false);
        btnluu.setEnabled(false);
        
        fChiTiet chitiet = new fChiTiet(txtMaHD.getText(), tenMenu, username,2);
        this.dispose();
        chitiet.setVisible(true);
        
    }//GEN-LAST:event_btnluuActionPerformed

    private void btnTaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(
                this,
                "Bạn có muốn thêm thông tin khách hàng mới?",
                "Thông báo",
                JOptionPane.YES_NO_OPTION);


        //xóa luôn hóa đơn
        if (n == JOptionPane.YES_OPTION) {
           fKhachHang khachHang = new fKhachHang(tenMenu, username);
            this.dispose();
            khachHang.setVisible(true);
        }
        
        
        txtMaHD.setText(AutoID.Instance().phatSinhIDDonHang());
        String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        txtNgayBan.setText(date);
        mahd_temp = txtMaHD.getText();
        btnTaoHD.setEnabled(false);
        btnthem.setEnabled(true);
        btnluu.setEnabled(true);
    }//GEN-LAST:event_btnTaoHDActionPerformed

    private void cbbmakhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbmakhItemStateChanged
        // TODO add your handling code here:
        String makh = cbbmakh.getSelectedItem().toString();

        DT_KhachHang k = KhachHang.Instance().getKHByID(makh);

        txtTenKH.setText(k.getTen());
        txtDiaChi.setText(k.getDiachi());
        txtSdt.setText(k.getSdt());

    }//GEN-LAST:event_cbbmakhItemStateChanged

    private void cbbMaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbMaNVItemStateChanged
        // TODO add your handling code here:
        String manv = cbbMaNV.getSelectedItem().toString();

        DT_NhanVien k = NhanVien.Instance().getNVByID(manv);

        txtTenNV.setText(k.getHoten());
    }//GEN-LAST:event_cbbMaNVItemStateChanged

    private void cbbmatvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbmatvItemStateChanged
        // TODO add your handling code here:

        String mstv = cbbmatv.getSelectedItem().toString();
        DT_Tivi k = Tivi.Instance().getTVByID(mstv);

        txtSLKho.setText("" + k.getSoluong());
        txtGia.setText(k.getGia() + "");
        txtTen.setText(k.getTentivi());
    }//GEN-LAST:event_cbbmatvItemStateChanged

    private void txtSLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLKeyPressed
        // TODO add your handling code here:
        String value = txtSL.getText();
        int sl = 0;

        char c = evt.getKeyChar();
        if (evt.getKeyChar() == '\b' || evt.getKeyChar() == '-' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            {
                txtSL.setEditable(true);

            }

        } else {
            txtSL.setEditable(false);
        }/*
        try {
            sl = Integer.parseInt(txtSL.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!");
        }
        thanhtien = sl * Integer.parseInt(txtGia.getText()) - Integer.parseInt(txtKhuyenMai.getText()) * sl * Integer.parseInt(txtGia.getText()) / 100;
        txtThanhTien.setText(thanhtien + "");*/
    }//GEN-LAST:event_txtSLKeyPressed

    private void txtSLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSLKeyTyped
        // TODO add your handling code here:
        int sl = 0, khuyenmai = 0;
        int dongia = Integer.parseInt(txtGia.getText());
        try {
            sl = Integer.parseInt(txtSL.getText());
            khuyenmai = Integer.parseInt(txtKhuyenMai.getText());
        } catch (Exception e) {
        }
        thanhtien = sl * dongia - khuyenmai * sl * dongia / 100;
        txtThanhTien.setText(thanhtien + "");
    }//GEN-LAST:event_txtSLKeyTyped

    private void txtKhuyenMaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhuyenMaiKeyPressed
        // TODO add your handling code here:
        String value = txtKhuyenMai.getText();
        int l = value.length();

        char c = evt.getKeyChar();
        if (evt.getKeyChar() == '\b' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && l < 2)) {
            txtKhuyenMai.setEditable(true);
        } else {
            txtKhuyenMai.setEditable(false);
        }
    }//GEN-LAST:event_txtKhuyenMaiKeyPressed

    private void txtKhuyenMaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhuyenMaiKeyTyped
        // TODO add your handling code here:
        int sl = 0, khuyenmai = 0;
        int dongia = Integer.parseInt(txtGia.getText());
        try {
            sl = Integer.parseInt(txtSL.getText());
            khuyenmai = Integer.parseInt(txtKhuyenMai.getText());
        } catch (Exception e) {
        }
        thanhtien = sl * dongia - khuyenmai * sl * dongia / 100;
        txtThanhTien.setText(thanhtien + "");
    }//GEN-LAST:event_txtKhuyenMaiKeyTyped

    private void TableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSanPhamMouseClicked
        // TODO add your handling code here:
        int dong = TableSanPham.getSelectedRow();
        TableModel model = TableSanPham.getModel();
        
        cbbmatv.setSelectedItem(model.getValueAt(dong, 0));
    }//GEN-LAST:event_TableSanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fLapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fLapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fLapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fLapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fLapHoaDon().setVisible(true);
            }
        });
    }
    //check null
    boolean kiemTraRong(JPanel panel) {
        for (Component c : panel.getComponents()) {
            if (c instanceof JTextField) {
                if (((JTextField) c).getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng không để trống!");
                    return false;
                }
            }

        }
        return true;
    }
    void LoadHeader(){
        TableSanPham.getColumnModel().getColumn(0).setHeaderValue("Mã Tivi");
        TableSanPham.getColumnModel().getColumn(1).setHeaderValue("Tên Tivi");
        TableSanPham.getColumnModel().getColumn(2).setHeaderValue("Giá");
        TableSanPham.getColumnModel().getColumn(3).setHeaderValue("Số lượng");
        TableSanPham.getColumnModel().getColumn(4).setHeaderValue("Thành tiền (chưa giảm giá)");
    }
    

    void LoadAllCbb() {
        DataProvider.Instance().LoadCbb(cbbMaNV, DataProvider.Instance().ExcuteQuery("select msnv from nhanvien where msnv != 'master'", null));
        DataProvider.Instance().LoadCbb(cbbmakh, DataProvider.Instance().ExcuteQuery("select mskh from khachhang where mskh != 'deleted'", null));
        DataProvider.Instance().LoadCbb(cbbmatv, DataProvider.Instance().ExcuteQuery("select mstivi from tivi where mstivi != 'EROR (DELETED)'", null));
    }

    void ThemHD() {
        if (!kiemTraRong(pnlTT)) {
            return;
        }
        
        String madonString, ngaybanString, makhString, khuyenmai, tongtienString;

        madonString = txtMaHD.getText();
        ngaybanString = txtNgayBan.getText();
        makhString = cbbmakh.getSelectedItem().toString();
        khuyenmai = txtKhuyenMai.getText();
        tongtienString = txtThanhTien.getText();
        int slkho = Integer.parseInt(txtSLKho.getText());

        String masp = cbbmatv.getSelectedItem().toString();
        String msnv = cbbMaNV.getSelectedItem().toString();

        int soluong = Integer.parseInt(txtSL.getText());

        if(soluong > slkho){
            JOptionPane.showMessageDialog(this, "Khổng đủ sản phẩm để bán!");
            return;
        }
        //them don hang
        try {
            DonHang.Instance().ThemDonHang(madonString, ngaybanString, makhString, khuyenmai, tongtienString, msnv);
        } catch (Exception ex) {
        }
        //them tt don hang
        if (soluong > 0) {
            //kiểm tra sản phẩm đã thêm vào đơn hàng chưa
            if (!TTDonHang.Instance().ktraSPTrongDonHang(masp, madonString)) {
                //nếu chưa -> them vào
                if (TTDonHang.Instance().ThemTTDonHang(masp, madonString, soluong)) {
                    Tivi.Instance().capNhatSLSP(masp, -soluong);
                    JOptionPane.showMessageDialog(this, "Đã thêm sảm phẩm!");
                }
            } //ngược lại
            else {
                //nếu có rồi -> cộng thêm
                if (TTDonHang.Instance().BoSungSoLuong(masp, soluong)) {
                    Tivi.Instance().capNhatSLSP(masp, -soluong);
                    JOptionPane.showMessageDialog(this, "Đã bổ sung số lượng sảm phẩm!");
                }
            }
        } else if (soluong < 0) {
            //kiểm tra coi sản phẩm này đã thêm vào đơn chưa
            if (!TTDonHang.Instance().ktraSPTrongDonHang(masp, madonString)) {
                //nếu chưa ->  thông báo là không có lấy gì trừ đi đây
                JOptionPane.showMessageDialog(this, "Sản phẩm chưa được thêm vào hóa đơn. Vui lòng chọn mua trước!");
            } else {
                //nếu có rồi -> xét coi số lượng có đủ để trừ đi hay không
                int soluongsp = TTDonHang.Instance().getSoLuongSP(madonString, masp);
                //đủ để trừ
                if (soluong + soluongsp > 0) {
                    // tiến hành trừ đi số lượng trong đơn hàng và công thêm sl đã trừ vào kho
                    TTDonHang.Instance().capNhatSL(madonString, masp, soluong + soluongsp);
                    //cập nhật vào kho
                    Tivi.Instance().capNhatSLSP(masp, -soluong);
                } // vừa đủ để trừ
                else if (soluong + soluongsp == 0) {
                    // tiến hành xóa đi sp trong đơn
                    TTDonHang.Instance().xoaSanPham(masp, madonString);
                    //cập nhật vào kho
                    Tivi.Instance().capNhatSLSP(masp, -soluong);
                } //quá nhiều để xóa
                else {
                    JOptionPane.showMessageDialog(this, "Số lượng nhiều hơn số sản phẩm đã thêm, không xóa được");
                }
            }
        } //số lượng = 0
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn số lượng khác 0 !");
        }

        LoadDSSanPham(madonString);
    }

    void LoadDSSanPham(String iddonhang) {
        TableSanPham.setModel(TTDonHang.Instance().LoadDSSP(iddonhang));
        cbbmatv.setSelectedIndex(1);
        LoadHeader();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSanPham;
    private javax.swing.JButton btnTaoHD;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbMaNV;
    private javax.swing.JComboBox<String> cbbmakh;
    private javax.swing.JComboBox<String> cbbmatv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbCore;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel pnlTT;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNgayBan;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtSLKho;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables
}
