
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author infov
 */
public class fMenuAdmin extends javax.swing.JFrame {


    /**
     * Creates new form fMenuAdmin
     */
    String usrename;
    public fMenuAdmin(String usernameString) {
        usrename = usernameString;
        initComponents();       
        this.setLocationRelativeTo(null);
        
    }
    String tenMenu = "Admin";

    private fMenuAdmin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuDoiMatKhau = new javax.swing.JMenuItem();
        jMenuDangXuat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuNhanVien = new javax.swing.JMenuItem();
        jMenuKhachHang = new javax.swing.JMenuItem();
        jMenuSanPham = new javax.swing.JMenuItem();
        jMenuThuongHieu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuDoanhThu = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuBanHang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ CỬA HÀNG TIVI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, -4, 890, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backround/backround.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/user_admin.png"))); // NOI18N
        jMenu1.setText("Tài khoản");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/doimatkhau.png"))); // NOI18N
        jMenuDoiMatKhau.setText("Đổi mật khẩu");
        jMenuDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDoiMatKhau);

        jMenuDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/logout.png"))); // NOI18N
        jMenuDangXuat.setText("Đăng xuất");
        jMenuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDangXuat);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/infomation.png"))); // NOI18N
        jMenu2.setText("Thông tin");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/staff.png"))); // NOI18N
        jMenuNhanVien.setText("Nhân viên");
        jMenuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuNhanVien);

        jMenuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/client.png"))); // NOI18N
        jMenuKhachHang.setText("Khách hàng");
        jMenuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKhachHangActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuKhachHang);

        jMenuSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/sanpham.png"))); // NOI18N
        jMenuSanPham.setText("Sản phẩm");
        jMenuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSanPhamActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSanPham);

        jMenuThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuThuongHieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/thuonghieu.png"))); // NOI18N
        jMenuThuongHieu.setText("Thương hiệu");
        jMenuThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuThuongHieuActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuThuongHieu);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/thong_ke.png"))); // NOI18N
        jMenu3.setText("Thống kê");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/doanhthu.png"))); // NOI18N
        jMenuDoanhThu.setText("Doanh thu");
        jMenuDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuDoanhThu);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/giaodich.png"))); // NOI18N
        jMenu4.setText("Giao dịch");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuBanHang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/TV.png"))); // NOI18N
        jMenuBanHang.setText("Bán hàng");
        jMenuBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBanHangActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuBanHang);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoiMatKhauActionPerformed

        fDoiMatKhau doiMatKhau = new fDoiMatKhau(tenMenu, usrename);
        this.dispose();
        doiMatKhau.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDoiMatKhauActionPerformed

    private void jMenuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDangXuatActionPerformed

        fDangNhap dangXuat = new fDangNhap();
        this.dispose();
        dangXuat.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDangXuatActionPerformed

    private void jMenuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNhanVienActionPerformed

        fNhanVien nhanVien = new fNhanVien(tenMenu, usrename);       
        this.dispose();
        nhanVien.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuNhanVienActionPerformed

    private void jMenuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKhachHangActionPerformed
        fKhachHang khachHang = new fKhachHang(tenMenu, usrename);
        this.dispose();
        khachHang.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuKhachHangActionPerformed

    private void jMenuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSanPhamActionPerformed

        fTiVi sanphamTiVi = new fTiVi(tenMenu, usrename);
        this.dispose();
        sanphamTiVi.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSanPhamActionPerformed

    private void jMenuThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuThuongHieuActionPerformed
 
        fHangSanXuat hangSanXuat = new fHangSanXuat(tenMenu, usrename);
        this.dispose();
        hangSanXuat.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuThuongHieuActionPerformed

    private void jMenuDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDoanhThuActionPerformed

        fDoanhThu doanhThu = new fDoanhThu(tenMenu, usrename);
        this.dispose();
        doanhThu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDoanhThuActionPerformed

    private void jMenuBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBanHangActionPerformed
        // TODO add your handling code here:
        fLapHoaDon laphd = new fLapHoaDon(tenMenu, usrename);
        this.dispose();
        laphd.setVisible(true);
    }//GEN-LAST:event_jMenuBanHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuBanHang;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDangXuat;
    private javax.swing.JMenuItem jMenuDoanhThu;
    private javax.swing.JMenuItem jMenuDoiMatKhau;
    private javax.swing.JMenuItem jMenuKhachHang;
    private javax.swing.JMenuItem jMenuNhanVien;
    private javax.swing.JMenuItem jMenuSanPham;
    private javax.swing.JMenuItem jMenuThuongHieu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
