/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Function.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.JobAttributes;
import java.awt.List;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.swingx.JXDatePicker;
import javax.swing.*;
import javax.swing.table.JTableHeader;

/**
 *
 * @author infov
 */
public class fNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form fNhanVien
     */
    private ArrayList<NhanVien> list;
    DefaultTableModel model;
    String tenMenu, username;

    public fNhanVien(String tenMenu, String usernameString) {
        initComponents();

        this.tenMenu = tenMenu;
        this.username = usernameString;
        this.setLocationRelativeTo(null);
        list = new ArrayList<>();
        model = (DefaultTableModel) TableNhanVien.getModel();

        model.setColumnIdentifiers(new Object[]{"Tên", "Tên", "Tên", "Tên", "Tên", "Tên", "Tên", "Tên"});

        //Đường viền panelMain
        Border panBorder = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        panelMain.setBorder(panBorder);

        LoadNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private fNhanVien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlTT = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaso = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        txtLuong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtHSLuong = new javax.swing.JTextField();
        dpNgaySinh = new org.jdesktop.swingx.JXDatePicker();
        iconAutoID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnInsertStaff = new javax.swing.JButton();
        btnDeteleStaff = new javax.swing.JButton();
        btnUpdateStaff = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        rdbMa = new javax.swing.JRadioButton();
        rdbTen = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNhanVien = new javax.swing.JTable();
        lblMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelMain.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        pnlTT.setBackground(new java.awt.Color(204, 255, 204));
        pnlTT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "THÔNG TIN CHI TIẾT NHÂN VIÊN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 10))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("MÃ SỐ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("TÊN");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("ĐỊA CHỈ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("GIỚI TÍNH");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("SỐ DT");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("NGÀY SINH");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("LƯƠNG");

        txtMaso.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtTen.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSDTKeyPressed(evt);
            }
        });

        rdbNam.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(rdbNam);
        rdbNam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rdbNam.setSelected(true);
        rdbNam.setText("Nam");

        rdbNu.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(rdbNu);
        rdbNu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rdbNu.setText("Nữ");

        txtLuong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLuongKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("HỆ SỐ LƯƠNG");

        txtHSLuong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtHSLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHSLuongKeyPressed(evt);
            }
        });

        dpNgaySinh.setDate(new Date());

        iconAutoID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/auto.png"))); // NOI18N
        iconAutoID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAutoIDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTTLayout = new javax.swing.GroupLayout(pnlTT);
        pnlTT.setLayout(pnlTTLayout);
        pnlTTLayout.setHorizontalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconAutoID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(rdbNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbNu)))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dpNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT))
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHSLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlTTLayout.setVerticalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtHSLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTTLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtMaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(rdbNam)
                                    .addComponent(rdbNu)
                                    .addComponent(iconAutoID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(pnlTTLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 10))); // NOI18N

        btnInsertStaff.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInsertStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/insertClient.png"))); // NOI18N
        btnInsertStaff.setText("THÊM");
        btnInsertStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertStaffActionPerformed(evt);
            }
        });

        btnDeteleStaff.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeteleStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/deteleClient.png"))); // NOI18N
        btnDeteleStaff.setText("XÓA");
        btnDeteleStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeteleStaffActionPerformed(evt);
            }
        });

        btnUpdateStaff.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdateStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/updateClient.png"))); // NOI18N
        btnUpdateStaff.setText("SỬA");
        btnUpdateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStaffActionPerformed(evt);
            }
        });

        btnReload.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/upload-24.png"))); // NOI18N
        btnReload.setText("TẢI LẠI");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("TÌM KIẾM: ");

        rdbMa.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup2.add(rdbMa);
        rdbMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMa.setText("Mã");

        rdbTen.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup2.add(rdbTen);
        rdbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbTen.setText("Tên");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInsertStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeteleStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbMa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(rdbTen)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(txtTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(rdbMa)
                            .addComponent(rdbTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDeteleStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TableNhanVien.setBackground(new java.awt.Color(204, 255, 204));
        TableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        TableNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableNhanVien);

        lblMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMenu.setText("MENU");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblMenu)
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertStaffActionPerformed

        ThemNhanVien();

        ThemTaiKhoan();

        LoadNhanVien();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertStaffActionPerformed

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked

        if (tenMenu.equalsIgnoreCase("admin")) {
            fMenuAdmin admin = new fMenuAdmin(username);
            this.dispose();
            admin.setVisible(true);
        } else {
            fMenuNhanVien nhanVien = new fMenuNhanVien(username);
            this.dispose();
            nhanVien.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuMouseClicked

    private void btnDeteleStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeteleStaffActionPerformed
        // TODO add your handling code here:
        XoaNhanVien();
        LoadNhanVien();
    }//GEN-LAST:event_btnDeteleStaffActionPerformed

    private void TableNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNhanVienMouseClicked
        // TODO add your handling code here:
        int dong = TableNhanVien.getSelectedRow();
        TableModel model = TableNhanVien.getModel();

        txtMaso.setText(model.getValueAt(dong, 0).toString());
        txtTen.setText(model.getValueAt(dong, 1).toString());
        txtDiaChi.setText(model.getValueAt(dong, 3).toString());
        txtSDT.setText(model.getValueAt(dong, 5).toString());
        txtLuong.setText(model.getValueAt(dong, 6).toString());
        txtHSLuong.setText(model.getValueAt(dong, 7).toString());

        if (model.getValueAt(dong, 2).equals("Nam")) {
            rdbNam.setSelected(true);
        } else {
            rdbNu.setSelected(true);
        }

        String dateString = model.getValueAt(dong, 4).toString();

        Date date = null;
        try {
            date = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(dateString);
        } catch (ParseException ex) {
            Logger.getLogger(fNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        dpNgaySinh.setDate(date);
    }//GEN-LAST:event_TableNhanVienMouseClicked

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        // TODO add your handling code here:
        LoadNhanVien();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnUpdateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStaffActionPerformed
        // TODO add your handling code here:
        SuaNhanVien();
        LoadNhanVien();
    }//GEN-LAST:event_btnUpdateStaffActionPerformed

    private void txtSDTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSDTKeyPressed
        // TODO add your handling code here:
        String value = txtSDT.getText();
        int l = value.length();

        char c = evt.getKeyChar();
        if (evt.getKeyChar() == '\b' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && l < 10)) {
            txtSDT.setEditable(true);
        } else {
            txtSDT.setEditable(false);
        }

    }//GEN-LAST:event_txtSDTKeyPressed

    private void txtLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLuongKeyPressed
        // TODO add your handling code here:
        String value = txtLuong.getText();
        int l = value.length();
        if (evt.getKeyChar() == '\b' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            txtLuong.setEditable(true);
        } else {
            txtLuong.setEditable(false);
        }
    }//GEN-LAST:event_txtLuongKeyPressed

    private void txtHSLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHSLuongKeyPressed
        // TODO add your handling code here:
        String value = txtHSLuong.getText();
        int l = value.length();
        if (evt.getKeyChar() == '\b' || evt.getKeyChar() == '.' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            txtHSLuong.setEditable(true);
        } else {
            txtHSLuong.setEditable(false);
        }
    }//GEN-LAST:event_txtHSLuongKeyPressed

    private void iconAutoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAutoIDMouseClicked
        // TODO add your handling code here:
        txtMaso.setText(AutoID.Instance().phatSinhIDNhanVien());

    }//GEN-LAST:event_iconAutoIDMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TimKiem();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fNhanVien().setVisible(true);
            }
        });
    }
    
    //set header
    void LoadHeader(){
        TableNhanVien.getColumnModel().getColumn(0).setHeaderValue("Mã nhân viên");
        TableNhanVien.getColumnModel().getColumn(1).setHeaderValue("Tên nhân viên");
        TableNhanVien.getColumnModel().getColumn(2).setHeaderValue("Giới tính");
        TableNhanVien.getColumnModel().getColumn(3).setHeaderValue("Địa chỉ");
        TableNhanVien.getColumnModel().getColumn(4).setHeaderValue("Năm sinh");
        TableNhanVien.getColumnModel().getColumn(5).setHeaderValue("Số điện thoại");
        TableNhanVien.getColumnModel().getColumn(6).setHeaderValue("Lương cơ bản");
        TableNhanVien.getColumnModel().getColumn(7).setHeaderValue("Hệ số lương");
    }

    //check null
    boolean kiemTraRong(JPanel panel) {
        for (Component c : panel.getComponents()) {
            if (c instanceof JTextField) {
                if (((JTextField) c).getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng không để trống!");
                    return false;
                }
            }

        }
        return true;
    }

    //tim
    void TimKiem() {
        if (rdbMa.isSelected()) {
            TableNhanVien.setModel(NhanVien.Instance().TimKiemNV("msnv", txtTimKiem.getText()));
        } else {
            TableNhanVien.setModel(NhanVien.Instance().TimKiemNV("hoten", txtTimKiem.getText()));
        }
    }

    @Override
    public void toBack() {
        super.toBack(); //To change body of generated methods, choose Tools | Templates.
    }

    //ham` load nhan vien
    void LoadNhanVien() {
        TableNhanVien.setModel(NhanVien.Instance().LoadNhanVien());
        LoadHeader();
    }

    //ham them nhan vien
    void ThemNhanVien() {
        if (!kiemTraRong(pnlTT)) {
            return;
        }
        String msnvString, hotenString, diachiString, gioitinhString, sdtString;
        String ngaySinh;
        int luong = 0;
        float HSLuong = 0;

        msnvString = txtMaso.getText();

        hotenString = txtTen.getText();

        if (rdbNam.isSelected()) {
            gioitinhString = "Nam";
        } else {
            gioitinhString = "Nữ";
        }

        diachiString = txtDiaChi.getText();

        sdtString = txtSDT.getText();

        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        ngaySinh = formater.format(dpNgaySinh.getDate());

        try {
            luong = Integer.parseInt(txtLuong.getText());

            HSLuong = Float.parseFloat(txtHSLuong.getText());
        } catch (Exception ex) {

        }

        if (!NhanVien.Instance().kiemTraNV(msnvString)) {
            NhanVien.Instance().ThemNV(msnvString, hotenString, gioitinhString, diachiString, ngaySinh, sdtString, luong, HSLuong);
        } else {
            JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại!");
        }

    }

    void ThemTaiKhoan() {
        String maso = txtMaso.getText();
        if (TaiKhoan.Instance().themTaiKhoan(maso)) {
            JOptionPane.showMessageDialog(this, "Đã tạo tài khoản \nUsername: " + maso + " \nPassword: 123 \nVui lòng đổi mật khẩu!");
        } else {
            JOptionPane.showMessageDialog(this, "Lõi nè");
        }
    }

    void XoaNhanVien() {
        int dong = TableNhanVien.getSelectedRow();
        if (dong == -1) {
            JOptionPane.showMessageDialog(this, "Bạn có chọn dòng nào đâuuuuuuuu !");
            return;
        }
        TableModel model = TableNhanVien.getModel();

        String maso = model.getValueAt(dong, 0).toString();

        if (TaiKhoan.Instance().xoaTaiKhoan(maso) && NhanVien.Instance().xoaNhanVien(maso)) {
            JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
        }

    }

    void SuaNhanVien() {
        int dong = TableNhanVien.getSelectedRow();
        if (dong == -1) {
            JOptionPane.showMessageDialog(this, "Bạn có chọn dòng nào đâuuuuuuuu !");
            return;
        }
        TableModel model = TableNhanVien.getModel();
        String maso = model.getValueAt(dong, 0).toString();

        String msnvString, hotenString, diachiString, gioitinhString, sdtString;
        String ngaySinh;
        int luong;
        float HSLuong;

        msnvString = txtMaso.getText();
        hotenString = txtTen.getText();
        if (rdbNam.isSelected()) {
            gioitinhString = "Nam";
        } else {
            gioitinhString = "Nữ";
        }
        diachiString = txtDiaChi.getText();
        sdtString = txtSDT.getText();

        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        ngaySinh = formater.format(dpNgaySinh.getDate());

        luong = Integer.parseInt(txtLuong.getText());
        HSLuong = Float.parseFloat(txtHSLuong.getText());

        if (NhanVien.Instance().suaNhanVien(maso, msnvString, hotenString, gioitinhString, diachiString, ngaySinh, sdtString, luong, HSLuong)) {
            JOptionPane.showMessageDialog(this, "Đã sửa thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNhanVien;
    private javax.swing.JButton btnDeteleStaff;
    private javax.swing.JButton btnInsertStaff;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnUpdateStaff;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private org.jdesktop.swingx.JXDatePicker dpNgaySinh;
    private javax.swing.JLabel iconAutoID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel pnlTT;
    private javax.swing.JRadioButton rdbMa;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JRadioButton rdbTen;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHSLuong;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaso;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

}
