
import Function.AutoID;
import Function.DataProvider;
import Function.NhanVien;
import Function.TTDonHang;
import Function.TaiKhoan;
import Function.ThuongHieu;
import Function.Tivi;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author infov
 */
public class fTiVi extends javax.swing.JFrame {

    /**
     * Creates new form fTiVi
     */
    String tenMenu, username;

    public fTiVi(String tenMenu, String usernameString) {
        initComponents();
        this.tenMenu = tenMenu;
        this.username = usernameString;
        
        if(tenMenu.equals("NhanVien"))
        {
            btnDeteleTiVi.setEnabled(false);
            btnInsertTiVi.setEnabled(false);
            btnUpdateTiVi.setEnabled(false);
        }

        this.setLocationRelativeTo(null);

        //Đường viền panelMain
        Border panBorder = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK);
        panelMain.setBorder(panBorder);

        LoadTivi();
        LoadCbbTH();
    }

    private fTiVi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlTT = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtIdTiVi = new javax.swing.JTextField();
        txtPriceTIVi = new javax.swing.JTextField();
        txtBaoHanh = new javax.swing.JTextField();
        cbbNameTiVi = new javax.swing.JComboBox<>();
        cbbStatusTiVi = new javax.swing.JComboBox<>();
        txtKichThuoc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtSluong = new javax.swing.JTextField();
        iconAutoID2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnInsertTiVi = new javax.swing.JButton();
        btnDeteleTiVi = new javax.swing.JButton();
        btnUpdateTiVi = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        rdbMa = new javax.swing.JRadioButton();
        rdbTen = new javax.swing.JRadioButton();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        rdbGia = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTiVi = new javax.swing.JTable();
        lblMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelMain.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("THÔNG TIN TIVI");

        pnlTT.setBackground(new java.awt.Color(204, 204, 204));
        pnlTT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "THÔNG TIN CHI TIẾT TIVI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 10))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("MÃ SỐ");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("TÊN HÃNG");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("GIÁ");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("KÍCH THƯỚC (INCH)");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("TÌNH TRẠNG");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("BẢO HÀNH");

        txtIdTiVi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtPriceTIVi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtPriceTIVi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceTIViKeyPressed(evt);
            }
        });

        txtBaoHanh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtBaoHanh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBaoHanhKeyPressed(evt);
            }
        });

        cbbNameTiVi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        cbbStatusTiVi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbbStatusTiVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Cũ" }));

        txtKichThuoc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtKichThuoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKichThuocKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("TÊN TIVI");

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("SỐ LƯỢNG");

        txtSluong.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtSluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSluongKeyPressed(evt);
            }
        });

        iconAutoID2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES_MENU_ADMIN/auto.png"))); // NOI18N
        iconAutoID2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAutoID2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTTLayout = new javax.swing.GroupLayout(pnlTT);
        pnlTT.setLayout(pnlTTLayout);
        pnlTTLayout.setHorizontalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(iconAutoID2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbNameTiVi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPriceTIVi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtSluong, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbStatusTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        pnlTTLayout.setVerticalGroup(
            pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTLayout.createSequentialGroup()
                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbbStatusTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtIdTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTTLayout.createSequentialGroup()
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlTTLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(txtSluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbbNameTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTTLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconAutoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(pnlTTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtPriceTIVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CHỨC NĂNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 10))); // NOI18N

        btnInsertTiVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnInsertTiVi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/insertClient.png"))); // NOI18N
        btnInsertTiVi.setText("THÊM");
        btnInsertTiVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertTiViActionPerformed(evt);
            }
        });

        btnDeteleTiVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDeteleTiVi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/deteleClient.png"))); // NOI18N
        btnDeteleTiVi.setText("XÓA");
        btnDeteleTiVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeteleTiViActionPerformed(evt);
            }
        });

        btnUpdateTiVi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdateTiVi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/updateClient.png"))); // NOI18N
        btnUpdateTiVi.setText("SỬA");
        btnUpdateTiVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTiViActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("TÌM KIẾM: ");

        rdbMa.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdbMa);
        rdbMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMa.setText("Mã");

        rdbTen.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdbTen);
        rdbTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbTen.setText("Tên");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/search.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        rdbGia.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdbGia);
        rdbGia.setText("Giá");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnInsertTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeteleTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbMa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(rdbTen)
                        .addGap(18, 18, 18)
                        .addComponent(rdbGia)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rdbMa)
                            .addComponent(rdbTen)
                            .addComponent(rdbGia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDeteleTiVi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertTiVi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TableTiVi.setBackground(new java.awt.Color(204, 204, 204));
        TableTiVi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableTiVi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTiViMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableTiVi);

        lblMenu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblMenu.setText("MENU");
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblMenu)
                        .addGap(332, 332, 332)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked

        if (tenMenu.equalsIgnoreCase("admin")) {
            fMenuAdmin admin = new fMenuAdmin(username);
            this.dispose();
            admin.setVisible(true);
        } else {
            fMenuNhanVien nhanVien = new fMenuNhanVien(username);
            this.dispose();
            nhanVien.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMenuMouseClicked

    private void btnInsertTiViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertTiViActionPerformed
        // TODO add your handling code here:
        ThemTivi();
        LoadTivi();
    }//GEN-LAST:event_btnInsertTiViActionPerformed

    private void txtKichThuocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKichThuocKeyPressed
        // TODO add your handling code here:
        checkKeyPressed(txtKichThuoc, evt);

    }//GEN-LAST:event_txtKichThuocKeyPressed

    private void txtPriceTIViKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceTIViKeyPressed
        // TODO add your handling code here:

        checkKeyPressed(txtPriceTIVi, evt);

    }//GEN-LAST:event_txtPriceTIViKeyPressed

    private void txtBaoHanhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBaoHanhKeyPressed
        // TODO add your handling code here:
        checkKeyPressed(txtBaoHanh, evt);

    }//GEN-LAST:event_txtBaoHanhKeyPressed

    private void txtSluongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSluongKeyPressed
        // TODO add your handling code here:
        checkKeyPressed(txtSluong, evt);
    }//GEN-LAST:event_txtSluongKeyPressed

    private void btnDeteleTiViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeteleTiViActionPerformed
        // TODO add your handling code here:
        XoaTivi();
        LoadTivi();
    }//GEN-LAST:event_btnDeteleTiViActionPerformed

    private void btnUpdateTiViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTiViActionPerformed
        // TODO add your handling code here:
        SuaTivi();
        LoadTivi();
    }//GEN-LAST:event_btnUpdateTiViActionPerformed

    private void iconAutoID2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAutoID2MouseClicked
        // TODO add your handling code here:
        txtIdTiVi.setText(AutoID.Instance().phatSinhIDTivi());

    }//GEN-LAST:event_iconAutoID2MouseClicked

    private void TableTiViMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTiViMouseClicked
        // TODO add your handling code here:
        int dong = TableTiVi.getSelectedRow();
        TableModel model = TableTiVi.getModel();

        txtIdTiVi.setText(model.getValueAt(dong, 0).toString());
        txtName.setText(model.getValueAt(dong, 1).toString());
        txtSluong.setText(model.getValueAt(dong, 7).toString());
        txtBaoHanh.setText(model.getValueAt(dong, 6).toString());
        txtPriceTIVi.setText(model.getValueAt(dong, 4).toString());
        txtKichThuoc.setText(model.getValueAt(dong, 3).toString());

        cbbStatusTiVi.setSelectedItem(model.getValueAt(dong, 5).toString());

        cbbNameTiVi.setSelectedItem(model.getValueAt(dong, 2).toString());

    }//GEN-LAST:event_TableTiViMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        TimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTiVi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTiVi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTiVi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTiVi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTiVi().setVisible(true);
            }
        });
    }
    
     //set header
    void LoadHeader(){
        TableTiVi.getColumnModel().getColumn(0).setHeaderValue("Mã Tivi");
        TableTiVi.getColumnModel().getColumn(1).setHeaderValue("Tên Tivi");
        TableTiVi.getColumnModel().getColumn(2).setHeaderValue("Tên hãng");
        TableTiVi.getColumnModel().getColumn(3).setHeaderValue("Kích thước");
        TableTiVi.getColumnModel().getColumn(4).setHeaderValue("Giá");
        TableTiVi.getColumnModel().getColumn(5).setHeaderValue("Bảo hành (tháng)");
        TableTiVi.getColumnModel().getColumn(6).setHeaderValue("Tình trạng");
        TableTiVi.getColumnModel().getColumn(7).setHeaderValue("Số lượng");
    }
    
     //check null
    boolean kiemTraRong(JPanel panel) {
        for (Component c : panel.getComponents()) {
            if (c instanceof JTextField) {
                if (((JTextField) c).getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng không để trống!");
                    return false;
                }
            }

        }
        return true;
    }
    
    //tim
    void TimKiem(){
        if(rdbMa.isSelected()){
            TableTiVi.setModel(Tivi.Instance().TimKiemTivi("mstivi", txtTimKiem.getText()));
        }
        else if(rdbTen.isSelected()){
            TableTiVi.setModel(Tivi.Instance().TimKiemTivi("tentivi", txtTimKiem.getText()));
        }
        else{
            TableTiVi.setModel(Tivi.Instance().TimKiemTivi("gia", txtTimKiem.getText()));
        }
    }

    //keypressed
    void checkKeyPressed(JTextField txt, java.awt.event.KeyEvent evt) {
        String value = txt.getText();
        int l = value.length();
        if (evt.getKeyChar() == '\b' || (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && l < 10)) {
            txt.setEditable(true);
        } else {
            txt.setEditable(false);
        }
    }

    //load cbb
    void LoadCbbTH() {
        DataProvider.Instance().LoadCbb(cbbNameTiVi, DataProvider.Instance().ExcuteQuery("select tenhang from hangtivi where mshang!=1", null));
    }

    //load tivi
    void LoadTivi() {
        TableTiVi.setModel(Tivi.Instance().LoadTivi());
        LoadHeader();
    }

    //them tivi
    void ThemTivi() {
        if (!kiemTraRong(pnlTT)) {
            return;
        }
        
        String masoString, tenString, tinhtrangString;
        int hang, gia, baohanh, kichthuoc, soluong;

        masoString = txtIdTiVi.getText();

        tenString = txtName.getText();

        hang = ThuongHieu.Instance().getIDHang(cbbNameTiVi.getSelectedItem().toString());

        kichthuoc = Integer.parseInt(txtKichThuoc.getText());

        gia = Integer.parseInt(txtPriceTIVi.getText());

        baohanh = Integer.parseInt(txtBaoHanh.getText());

        tinhtrangString = cbbStatusTiVi.getSelectedItem().toString();

        soluong = Integer.parseInt(txtSluong.getText());

        if (!Tivi.Instance().kiemTraTivi(masoString)) {
            if (Tivi.Instance().ThemTivi(masoString, tenString, hang, kichthuoc, gia, baohanh, tinhtrangString, soluong)) {
                JOptionPane.showMessageDialog(this, "Thêm tivi thành công rực rỡ!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Mã số tivi đã tồn tại!");
        }

    }

    ////xoa tivi
    void XoaTivi() {
        int dong = TableTiVi.getSelectedRow();
        if(dong == -1)
        {
            JOptionPane.showMessageDialog(this, "Bạn có chọn dòng nào đâuuuuuuuu !");
            return;
        }
        TableModel model = TableTiVi.getModel();

        String maso = model.getValueAt(dong, 0).toString();

        if (TTDonHang.Instance().capNhatSanPhamBiXoa(maso)) {
            if (Tivi.Instance().xoaTivi(maso)) {
                JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
            }
        }
    }

    //sua
    void SuaTivi() {

        int dong = TableTiVi.getSelectedRow();
        if(dong == -1)
        {
            JOptionPane.showMessageDialog(this, "Bạn có chọn dòng nào đâuuuuuuuu !");
            return;
        }
        TableModel model = TableTiVi.getModel();
        String maso = model.getValueAt(dong, 0).toString();

        String masoString, tenString, tinhtrangString;
        int hang, gia, baohanh, kichthuoc, soluong;

        masoString = txtIdTiVi.getText();

        tenString = txtName.getText();

        hang = ThuongHieu.Instance().getIDHang(cbbNameTiVi.getSelectedItem().toString());

        kichthuoc = Integer.parseInt(txtKichThuoc.getText());

        gia = Integer.parseInt(txtPriceTIVi.getText());

        baohanh = Integer.parseInt(txtBaoHanh.getText());

        tinhtrangString = cbbStatusTiVi.getSelectedItem().toString();

        soluong = Integer.parseInt(txtSluong.getText());

        if (Tivi.Instance().suaTivi(maso, masoString, tenString, hang, kichthuoc, gia, baohanh, tinhtrangString, soluong)) {
            JOptionPane.showMessageDialog(this, "Đã sửa thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại!");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableTiVi;
    private javax.swing.JButton btnDeteleTiVi;
    private javax.swing.JButton btnInsertTiVi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdateTiVi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbNameTiVi;
    private javax.swing.JComboBox<String> cbbStatusTiVi;
    private javax.swing.JLabel iconAutoID2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel pnlTT;
    private javax.swing.JRadioButton rdbGia;
    private javax.swing.JRadioButton rdbMa;
    private javax.swing.JRadioButton rdbTen;
    private javax.swing.JTextField txtBaoHanh;
    private javax.swing.JTextField txtIdTiVi;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPriceTIVi;
    private javax.swing.JTextField txtSluong;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
