/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package duan;

/**
 *
 * @author infov
 */
public class Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form Main_Form
     */
    public Main_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        menuThemSinhVien = new javax.swing.JButton();
        menuDanhSachSinhVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        menuThemSinhVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuThemSinhVien.setText("Thêm sinh viên");
        menuThemSinhVien.setFocusable(false);
        menuThemSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuThemSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuThemSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThemSinhVienActionPerformed(evt);
            }
        });
        jToolBar1.add(menuThemSinhVien);

        menuDanhSachSinhVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menuDanhSachSinhVien.setText("Danh sách sinh viên");
        menuDanhSachSinhVien.setFocusable(false);
        menuDanhSachSinhVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuDanhSachSinhVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuDanhSachSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDanhSachSinhVienActionPerformed(evt);
            }
        });
        jToolBar1.add(menuDanhSachSinhVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 327, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuThemSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThemSinhVienActionPerformed

        Add_Form form=new Add_Form();
        
        form.setDefaultCloseOperation(Add_Form.DISPOSE_ON_CLOSE);//Hủy khi đóng form
        form.setLocationRelativeTo(null);//Đưa form về giữa màn hình
        form.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThemSinhVienActionPerformed

    private void menuDanhSachSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDanhSachSinhVienActionPerformed

        List_Form form=new List_Form();
        
        form.setDefaultCloseOperation(List_Form.DISPOSE_ON_CLOSE);//Hủy khi đóng form
        form.setLocationRelativeTo(null);//Đưa form về giữa màn hình
        form.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDanhSachSinhVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton menuDanhSachSinhVien;
    private javax.swing.JButton menuThemSinhVien;
    // End of variables declaration//GEN-END:variables
}
